namespace SpriteKind {
    export const OBJETO = SpriteKind.create()
}
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile0`, function (sprite, location) {
    info.changeLifeBy(2)
    tiles.setTileAt(location, sprites.dungeon.darkGroundSouthEast1)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile1`, function (sprite, location) {
    info.changeScoreBy(100)
    tiles.setTileAt(location, sprites.dungeon.chestOpen)
})
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    tiro = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . 2 2 2 2 2 . . . . . . . 
        . . . 2 2 4 4 4 2 2 . . . . . . 
        . . 2 4 4 5 5 5 4 2 2 2 . . . . 
        . . 2 2 4 5 5 5 4 4 4 2 . . . . 
        . . . 2 4 4 4 4 4 4 4 2 . . . . 
        . . . 2 2 2 2 2 4 2 2 2 . . . . 
        . . . . . . . 2 2 2 . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, eu, controller.dx(8000), controller.dy(8000))
    music.play(music.createSoundEffect(WaveShape.Triangle, 1194, 200, 255, 0, 75, SoundExpressionEffect.None, InterpolationCurve.Curve), music.PlaybackMode.UntilDone)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile`, function (sprite, location) {
    info.changeScoreBy(10)
    tiles.setTileAt(location, sprites.dungeon.darkGroundSouthEast1)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (eu.isHittingTile(CollisionDirection.Bottom)) {
        eu.vy += -90
    }
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    eu,
    [img`
        ..............................
        ..............................
        ..............................
        .............11...............
        ............1.1...............
        ..............1...............
        ..............1...............
        .............111..............
        ..............................
        ............ffff..............
        ..........ff1111ff............
        .........fb111111bf...........
        .........f1111111df...........
        ........fd1111111ddf..........
        ........fd111111dddf..........
        ........fd111ddddddf..........
        ........fd1dfbddddbf..........
        ........fbddfcdbbbcf..........
        .........f11111bbcf...........
        .........f1b1fffff............
        .........fbfc111bf............
        ..........ff1b1bff............
        ...........fbfbfff.f..........
        ............ffffffff..........
        ..............fffff...........
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        `,img`
        ..............................
        ..............................
        ............11................
        ...........1.1................
        .............1................
        .............1................
        .............1................
        ............111...............
        ..............................
        ..........fffff...............
        .........f11111ff.............
        ........fb111111bf............
        ........f1111111dbf...........
        .......fd111111dddf...........
        .......fd11111ddddf...........
        .......fd11dddddddf...........
        .......f111dddddddf...........
        .......f11fcddddddf...........
        ......fb1111bdddbf............
        ......f1b1bdfcfff.............
        ......fbfbffffffff............
        .......fffffffffff.ff.........
        ............ffffffff..........
        .........f1b1bffffff..........
        .........fbfbffffff...........
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        `],
    500,
    true
    )
})
function mudar_de_fase () {
    let list: tiles.TileMapData[] = []
    tiles.setCurrentTilemap(list[0])
    tiles.placeOnRandomTile(eu, assets.tile`transparency16`)
}
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    eu,
    [img`
        ........................
        ........................
        ............11..........
        ............1.1.........
        ............1...........
        ............1...........
        ...........111..........
        ........................
        ..........fffff.........
        ........ff11111f........
        .......fb111111bf.......
        ......fbd1111111f.......
        ......fddd111111df......
        ......fdddd11111df......
        ......fddddddd11df......
        ......fddddddd111f......
        ......fddddddcf11f......
        .......fbdddb1111bf.....
        ........fffcfdb1b1f.....
        .......ffffffffbfbf.....
        ....ff.fffffffffff......
        .....ffffffff...........
        .....ffffffb1b1f........
        ......ffffffbfbf........
        `,img`
        ............11..........
        ............1.1.........
        ............1...........
        ............1...........
        ...........111..........
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......fd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fbddddbfd1df......
        ......fcbbbdcfddbf......
        .......fcbb11111f.......
        ........fffff1b1f.......
        ........fb111cfbf.......
        ........ffb1b1ff........
        ......f.fffbfbf.........
        ......ffffffff..........
        .......fffff............
        ........................
        ........................
        `],
    500,
    true
    )
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile2`, function (sprite, location) {
    info.changeLifeBy(-1)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile5`, function (sprite, location) {
    info.changeLifeBy(-1)
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    sprites.destroy(otherSprite)
    for (let index = 0; index < 0; index++) {
        inimigo = sprites.create(img`
            . . f f f . . . . . . . . f f f 
            . f f c c . . . . . . f c b b c 
            f f c c . . . . . . f c b b c . 
            f c f c . . . . . . f b c c c . 
            f f f c c . c c . f c b b c c . 
            f f c 3 c c 3 c c f b c b b c . 
            f f b 3 b c 3 b c f b c c b c . 
            . c b b b b b b c b b c c c . . 
            . c 1 b b b 1 b b c c c c . . . 
            c b b b b b b b b b c c . . . . 
            c b c b b b c b b b b f . . . . 
            f b 1 f f f 1 b b b b f c . . . 
            f b b b b b b b b b b f c c . . 
            . f b b b b b b b b c f . . . . 
            . . f b b b b b b c f . . . . . 
            . . . f f f f f f f . . . . . . 
            `, SpriteKind.Enemy)
        inimigo.setPosition(112, 31)
    }
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.collectibleInsignia, function (sprite, location) {
    tiles.placeOnRandomTile(eu, sprites.dungeon.collectibleInsignia)
})
let tiro: Sprite = null
let inimigo: Sprite = null
let eu: Sprite = null
tiles.setCurrentTilemap(tilemap`level2`)
eu = sprites.create(img`
    ........................
    ........................
    ........................
    ..........11............
    .........1.1............
    ...........1............
    ...........1............
    ...........1............
    ...........1............
    ..........111...........
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
eu.setStayInScreen(true)
eu.ay = 120
inimigo = sprites.create(img`
    . . f f f . . . . . . . . f f f 
    . f f c c . . . . . . f c b b c 
    f f c c . . . . . . f c b b c . 
    f c f c . . . . . . f b c c c . 
    f f f c c . c c . f c b b c c . 
    f f c 3 c c 3 c c f b c b b c . 
    f f b 3 b c 3 b c f b c c b c . 
    . c b b b b b b c b b c c c . . 
    . c 1 b b b 1 b b c c c c . . . 
    c b b b b b b b b b c c . . . . 
    c b c b b b c b b b b f . . . . 
    f b 1 f f f 1 b b b b f c . . . 
    f b b b b b b b b b b f c c . . 
    . f b b b b b b b b c f . . . . 
    . . f b b b b b b c f . . . . . 
    . . . f f f f f f f . . . . . . 
    `, SpriteKind.Enemy)
inimigo.follow(eu, 40)
inimigo.setPosition(116, 37)
info.setLife(3)
let bau = sprites.create(img`
    c c b b b b b b b b b b b b c c 
    c b e 4 4 4 4 4 4 4 4 4 4 e b c 
    b e 4 4 4 4 4 4 4 4 4 4 4 4 e b 
    b e 4 4 4 4 4 4 4 4 4 4 4 4 e b 
    b e 4 4 4 4 4 4 4 4 4 4 4 4 e b 
    b e e 4 4 4 4 4 4 4 4 4 4 e e b 
    b e e e e e e e e e e e e e e b 
    b e e e e e e e e e e e e e e b 
    b b b b b b b d d b b b b b b b 
    c b b b b b b c c b b b b b b c 
    c c c c c c b c c b c c c c c c 
    b e e e e e c b b c e e e e e b 
    b e e e e e e e e e e e e e e b 
    b c e e e e e e e e e e e e c b 
    b b b b b b b b b b b b b b b b 
    c b b c c c c c c c c c c b b c 
    `, SpriteKind.OBJETO)
tiles.placeOnRandomTile(eu, sprites.dungeon.stairEast)
controller.moveSprite(eu, 100, 0)
tiles.placeOnRandomTile(bau, sprites.dungeon.chestOpen)
scene.cameraFollowSprite(eu)
animation.runImageAnimation(
inimigo,
[img`
    . . f f f . . . . . . . . f f f 
    . f f c c . . . . . . f c b b c 
    f f c c . . . . . . f c b b c . 
    f c f c . . . . . . f b c c c . 
    f f f c c . c c . f c b b c c . 
    f f c 3 c c 3 c c f b c b b c . 
    f f b 3 b c 3 b c f b c c b c . 
    . c 1 b b b 1 b c b b c c c . . 
    . c 1 b b b 1 b b c c c c . . . 
    c b b b b b b b b b c c . . . . 
    c b 1 f f 1 c b b b b f . . . . 
    f f 1 f f 1 f b b b b f c . . . 
    f f 2 2 2 2 f b b b b f c c . . 
    . f 2 2 2 2 b b b b c f . . . . 
    . . f b b b b b b c f . . . . . 
    . . . f f f f f f f . . . . . . 
    `,img`
    . . f f f . . . . . . . . . . . 
    f f f c c . . . . . . . . f f f 
    f f c c c . c c . . . f c b b c 
    f f c 3 c c 3 c c f f b b b c . 
    f f c 3 b c 3 b c f b b c c c . 
    f c b b b b b b c f b c b c c . 
    c c 1 b b b 1 b c b b c b b c . 
    c b b b b b b b b b c c c b c . 
    c b 1 f f 1 c b b c c c c c . . 
    c f 1 f f 1 f b b b b f c . . . 
    f f f f f f f b b b b f c . . . 
    f f 2 2 2 2 f b b b b f c c . . 
    . f 2 2 2 2 2 b b b c f . . . . 
    . . f 2 2 2 b b b c f . . . . . 
    . . . f f f f f f f . . . . . . 
    . . . . . . . . . . . . . . . . 
    `,img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . c c . c c . . . . . . . . 
    . . f 3 c c 3 c c c . . . . . . 
    . f c 3 b c 3 b c c c . . . . . 
    f c b b b b b b b b f f . . . . 
    c c 1 b b b 1 b b b f f . . . . 
    c b b b b b b b b c f f f . . . 
    c b 1 f f 1 c b b f f f f . . . 
    f f 1 f f 1 f b c c b b b . . . 
    f f f f f f f b f c c c c . . . 
    f f 2 2 2 2 f b f b b c c c . . 
    . f 2 2 2 2 2 b c c b b c . . . 
    . . f 2 2 2 b f f c c b b c . . 
    . . . f f f f f f f c c c c c . 
    . . . . . . . . . . . . c c c c 
    `,img`
    . f f f . . . . . . . . f f f . 
    f f c . . . . . . . f c b b c . 
    f c c . . . . . . f c b b c . . 
    c f . . . . . . . f b c c c . . 
    c f f . . . . . f f b b c c . . 
    f f f c c . c c f b c b b c . . 
    f f f c c c c c f b c c b c . . 
    . f c 3 c c 3 b c b c c c . . . 
    . c b 3 b c 3 b b c c c c . . . 
    c c b b b b b b b b c c . . . . 
    c 1 1 b b b 1 1 b b b f c . . . 
    f b b b b b b b b b b f c c . . 
    f b c b b b c b b b b f . . . . 
    . f 1 f f f 1 b b b c f . . . . 
    . . f b b b b b b c f . . . . . 
    . . . f f f f f f f . . . . . . 
    `,img`
    . f f f . . . . . . . . f f f . 
    . c b b c f . . . . . . . c f f 
    . . c b b c f . . . . . . c c f 
    . . c c c b f . . . . . . . f c 
    . . c c b b f f . . . . . f f c 
    . . c b b c b f c c . c c f f f 
    . . c b c c b f c c c c c f f f 
    . . . c c c b c b 3 c c 3 c f . 
    . . . c c c c b b 3 c b 3 b c . 
    . . . . c c b b b b b b b b c c 
    . . . c f b b b 1 1 b b b 1 1 c 
    . . c c f b b b b b b b b b b f 
    . . . . f b b b b c b b b c b f 
    . . . . f c b b b 1 f f f 1 f . 
    . . . . . f c b b b b b b f . . 
    . . . . . . f f f f f f f . . . 
    `,img`
    f f f . . . . . . . . f f f . . 
    c b b c f . . . . . . c c f f . 
    . c b b c f . . . . . . c c f f 
    . c c c b f . . . . . . c f c f 
    . c c b b c f . c c . c c f f f 
    . c b b c b f c c 3 c c 3 c f f 
    . c b c c b f c b 3 c b 3 b f f 
    . . c c c b b c b 1 b b b 1 c . 
    . . . c c c c b b 1 b b b 1 c . 
    . . . . c c b b b b b b b b b c 
    . . . . f b b b b c 1 f f 1 b c 
    . . . c f b b b b f 1 f f 1 f f 
    . . c c f b b b b f 2 2 2 2 f f 
    . . . . f c b b b b 2 2 2 2 f . 
    . . . . . f c b b b b b b f . . 
    . . . . . . f f f f f f f . . . 
    `],
500,
true
)
forever(function () {
    effects.starField.startScreenEffect(5000)
})
